# name: Auto Deploy to Release Server
# on:
#   push:
#     branches:
#       - main
#       - release
# jobs:

#   build:
#     name: deploy-release
#     runs-on: ubuntu-latest
#     steps:
#       - name: deploy to release server
#         if: github.ref == 'refs/heads/main'
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: 82.180.137.15
#           username: root
#           password: ${{ secrets.PASSWORD }}
#           port: 22
#           script: |
#             cd /www/wwwroot/multi-backend.2025fc.xyz/multi-backend &&
#             git pull --rebase origin main &&
#             /www/server/nodejs/v20.16.0/bin/pnpm install &&
#             git checkout -f . &&
#             npm run build &&
#             pm2 restart multi-backend && node dist/bot/index.js


