name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 107.191.52.157
          username: root
          password: )3zE_2VQe%Nks9M?
          port: 22
          script: cd /www/wwwroot/ordersystem-new.2024fc.xyz/task-backend && git pull --rebase origin main && /www/server/nodejs/v20.12.0/bin/pnpm install && git checkout -f . && npm run build && cp -a src/uploads dist && pm2 restart dist/index.js