name: remote ssh command
on:
  push:
    branches:
      - main
      - release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to release server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.180.137.15
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/account-backend.2025fc.xyz/account-bot-backend &&
            git pull --rebase origin main &&
            /www/server/nodejs/v20.16.0/bin/pnpm install --registry=https://registry.npmjs.org &&
            git checkout -f . &&
            npm run build &&
            pm2 restart billbackend


