name: remote ssh command
on:
  push:
    branches:
      - main
      - release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to release server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.180.137.15
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/account-backend.2025fc.xyz/account-bot-backend
            git pull --rebase origin main
            /www/server/nodejs/v20.16.0/bin/pnpm install
            git checkout -f .
            npm run build &&
            pm2 restart billbackend

      # - name: deploy to main server
      #   if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: 3.107.241.66
      #     username: ubuntu  # Keep ubuntu as login user
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # 替换为PEM证书内容
      #     # password: ${{ secrets.CLIENT_PASSWORD }}  # 删除密码认证
      #     port: 22
      #     script: |
      #       sudo -i bash << 'EOF'  # Switch to root user in script execution
      #       cd /www/wwwroot/mev-bot-backend
      #       git pull --rebase origin main
      #       /www/server/nodejs/v22.14.0/bin/pnpm install
      #       git checkout -f . 
      #       npm run build &&
      #       pm2 restart mevbackend
      #       EOF
