name: Auto Deploy to Client Server

on:
  push:
    branches:
      - main

# on:
#   workflow_dispatch:  # 手动触发配置
#     inputs:
#       branch:
#         description: '需要部署的分支'
#         required: true
#         default: 'main'

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 7771207574
          token: 8436846375:AAHrFfGzaUUzxZZZjBWJQZ75Ve7r2m7CScs
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      - name: Deploy to client server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.180.137.15
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/multi-backend.2025fc.xyz/multi-backend-remote &&
            git pull --rebase origin ${GITHUB_REF##*/} &&
            /www/server/nodejs/v20.16.0/bin/pnpm install &&
            git checkout -f . &&
            npm run build &&
            npm run copy-to-remote